# Generated by Django 3.2.5 on 2021-07-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('ram', models.IntegerField()),
                ('cpu', models.IntegerField()),
                ('display', models.IntegerField()),
            ],
            options={
                'verbose_name': 'PC',
                'db_table': 'PCs',
            },
        ),
    ]
